### ISSUE TITLE
Umlizenzierung von y4f auf AGPLv3

### ISSUE THREAD

**Issue by FUH22860** [yummy4friends/y4f#2]
Da y4f über ein Netzwerk verwendet werden kann und GPLv3 leider uns von SAAS Loophole nicht schützt, würde ich empfehlen auf AGPLv3 zu wechseln.

Wenn ihr einverstanden seit zu wechseln müsst ihr nur diesen Paragraph schreiben.

```
Ich, <Name> gebe hiermit die Erlaubnis y4f unter der GNU Affero General Public License zu umlizenzieren.

Ein Teil der von <Benutzername> vorgenommenen commits unterliegen dem Copyright von <Name>.
Und ich erlaube hiermit dem yummy4friends Projektteam, y4f zu umlizenzieren,
einschließlich aller vergangenen, gegenwärtigen und zukünftigen Beiträge des oben genannten Autors. 
```

@MET18937 ✔️
@FUH22860 ✔️
@GEI22857 ✔️
@zha19115 ✔️

**Comment by FUH22860** [comment]
Ich, Andre Fuhry gebe hiermit die Erlaubnis y4f unter der GNU Affero General Public License zu umlizenzieren.

Ein Teil der von FUH22860 vorgenommenen commits unterliegen dem Copyright von Andre Fuhry.
Und ich erlaube hiermit dem yummy4friends Projektteam, y4f zu umlizenzieren,
einschließlich aller vergangenen, gegenwärtigen und zukünftigen Beiträge des oben genannten Autors.

**Comment by GEI22857** [comment]
Ich, Tamara Geiter gebe hiermit die Erlaubnis y4f unter der GNU Affero General Public License zu umlizenzieren.

Ein Teil der von GEI22857 vorgenommenen commits unterliegen dem Copyright von Tamara Geiter.
Und ich erlaube hiermit dem yummy4friends Projektteam, y4f zu umlizenzieren,
einschließlich aller vergangenen, gegenwärtigen und zukünftigen Beiträge des oben genannten Autors.

**Comment by zha19115** [comment]
Ich , Anni Zhan gebe hiermit die Erlaubnis y4f unter der GNU Affero General Public License zu umlizenzieren.

Ein Teil der von zha19115 vorgenommenen commits unterliegen dem Copyright von <Name>.
Und ich erlaube hiermit dem yummy4friends Projektteam, y4f zu umlizenzieren,
einschließlich aller vergangenen, gegenwärtigen und zukünftigen Beiträge des oben genannten Autors.

**Comment by MET18937** [comment]
Ich, Markus Metz gebe hiermit die Erlaubnis y4f unter der GNU Affero General Public License zu umlizenzieren.

Ein Teil der von MET18937 vorgenommenen commits unterliegen dem Copyright von .
Und ich erlaube hiermit dem yummy4friends Projektteam, y4f zu umlizenzieren,
einschließlich aller vergangenen, gegenwärtigen und zukünftigen Beiträge des oben genannten Autors.

**Comment by FUH22860** [comment]
Hiermit schließe ich das issue und ändere die lizenz von y4f auf AGPLv3.
